### ISSUE TITLE
[RFC] Switch to font-display optional

### ISSUE THREAD

**Issue by justman00** [sumup-oss/circuit-ui#1001]
## Suggested change

I suggest moving from `font-display: swap;` to `optional`. Currently, on the website, we are experiencing FOUT(Flash of Unstyled Text), which leads to text jumping from line to line, not the perfect experience for users and a trigger in LCP, inflating that value, as well as higher and desirable CLS. Example below:

https://user-images.githubusercontent.com/36477870/123383797-49850180-d59c-11eb-811d-2b818fea1c2e.mov

For more context, this is a [nice read](https://www.industrialempathy.com/posts/high-performance-web-font-loading/#stop-worrying-and-use-font-display%3A-optional), explaining how we got here and why `font-display: optional;` is the only solution that we can rely on.

## Alternatives

I have explored with all the other `font-display` options out there, and out of all of them, either `swap` or `optional` I can see as the winners.

## Potential downsides

Lack of brand experience for all the SumUp applications, however all of the other ones are apps that merchants tend to come back to very often, such as the dashboard or partner portal, and the lack of custom brand font is going to be only the first time they visit any app.

We are planning on trying this out on real users very soon on the marketing website, [PR ref](https://github.com/sumup/website/pull/2215), so we don't have any data right now. One more downside is that we can not track what users get the custom font and what users get the fallback ones, as currently it is not supported to check the rendered font of an element programmatically.

**Comment by robinmetral** [comment]
I'm totally in favor of this if your experience with it on the website is positive 👍

**Comment by justman00** [comment]
> I'm totally in favor of this if your experience with it on the website is positive 👍

Hey Robin, so this has been running on the marketing website for a month or so, and in fact, there is no noticeable impact on the business metrics, but there is quite a substantial one if we look at performance metrics, in particular, LCP:
<img width="750" alt="Screenshot 2021-08-16 at 16 33 23" src="https://user-images.githubusercontent.com/36477870/129572026-442122d3-4e59-4dc2-b06d-81feb7a1ede1.png">

**Comment by justman00** [comment]
great to see this moving forward!
