### ISSUE TITLE
Type of ref prop on Input is incompatible with reference to input

### ISSUE THREAD

**Issue by felixjung** [sumup-oss/circuit-ui#1025]
## Describe the bug

When you pass a reference to an input element to the `ref` prop of the `Input` component, the TypeScript compiler will give an error because `Ref<HTMLInputElement>` is incompatible with `Ref<HTMLInputElement & HTMLTextAreaElement>`.

**Example**

```tsx
const input = useRef<HTMLInputElement>(null)

return <Input ref={input} {...props} />
```

I think the current type of the `ref` prop cannot actually exist. You cannot have a ref to an element that is both an input element _and_ a textarea element (i.e. an intersection). In this example I would expect a union type (i.e., `HTMLInputElement | HTMLTextAreaElement`).

Overall I don't think that we can just reuse the `Input` component as `TextArea` using the `as` prop the way we do now. I've tried to do a quickfix of this but failed pretty quickly.

**Comment by felixjung** [comment]
Interestingly enough, I can create a ref for the intersection type we need and pass it down. Feels kinda wrong though.

**Comment by connor-baer** [comment]
@felixjung Did you see my comment on your closed PR? https://github.com/sumup-oss/circuit-ui/pull/1024#discussion_r665943699

**Comment by felixjung** [comment]
Nope, but thanks!
