### ISSUE TITLE
[Modal] Story is broken

### ISSUE THREAD

**Issue by dmitri-suvorov-sumup** [sumup-oss/circuit-ui#1105]
## Describe the bug

The modal story is broken.

## Steps to reproduce

1. Go to https://circuit.sumup.com/?path=/story/components-modal--base
2. Open DevTools
3. See the error in the console: `TypeError: Converting circular structure to JSON`

## Expected behavior

The story should be displayed on the screen.

## Specifications

* Browser: Chrome 92
* OS: macOS Big Sur 11.5.1
 
## Screenshot

![Screenshot 2021-08-11 at 14 22 46](https://user-images.githubusercontent.com/53574544/129022894-59fc7897-724c-4314-b007-944df50a4230.png)

**Comment by robinmetral** [comment]
Oops, thanks for reporting @dmitri-suvorov-sumup! Will take a look
