### ISSUE TITLE
userEvent.type() puts in a reversed string into the Input

### ISSUE THREAD

**Issue by mykolaharmash** [sumup-oss/circuit-ui#1111]
## Describe the bug

When testing with `@testing-library/user-event` and trying to type into the `Input` using `userEvent.type()` method, the value in the input ends up being reversed.

## Steps to reproduce

1. In your test call `userEvent.type(testInput, '123')`
2. `console.log(testInput.value)`
3. See `321`

## Specifications

* @testing-library/react@12.0.0
* @testing-library/user-event@13.1.9
* jest@24.9.0

## Additional context

This issue seemingly [has been resolved](https://github.com/testing-library/user-event/issues/369) already, but when used with Circuit UI Input I still see it.

**Comment by connor-baer** [comment]
Thanks for the report, @mykolaharmash! Can you confirm that you're referring to the Input and not the CurrencyInput? 

It would make sense to see such a bug in the CurrencyInput which formats the input value. The Input component doesn't have any internal state and directly forwards the `value` and `onChange` props to the `input` element. 

Could you try to run the same test, but replace the Circuit UI `Input` with the HTML `input` element?

**Comment by mykolaharmash** [comment]
Just checked, I see this issue on `SearchInput`, but from what I can see it also does not add any internal state. My code looks like this:

```
const [searchString, setSearchString] = useState('')

const onSearchInputChange = useCallback(
    (event) => setSearchString(event.target.value),
    []
)

return (
    <SearchInput
        label={label}
        hideLabel
        value={searchString}
        placeholder={placeholder}
        onChange={onSearchInputChange}
        noMargin
   />
)

```

For further investigation, @robinmetral has volunteered, but I'm happy to help if needed 😉

**Comment by bodhidharma-joe** [comment]
Downgrading to 12.0.4 fixed it for me

**Comment by terraelise** [comment]
> Downgrading to 12.0.4 fixed it for me

Same, was on 13.5.0 but had to go back to 12.0.4 for the fix.

**Comment by connor-baer** [comment]
That seems to confirm that the issue lies with `@testing-library/user-event` and not with Circuit UI, so I’m gonna go ahead and close this issue.
