### ISSUE TITLE
Input borders are cropped when wrapped with collapsible content using useCollapsible

### ISSUE THREAD

**Issue by mykolaharmash** [sumup-oss/circuit-ui#1112]
## Describe the bug

Form elements overflow the container which uses styles provided by `useCollapsible` hook.

<img width="668" alt="CleanShot 2021-08-13 at 10 39 04@2x" src="https://user-images.githubusercontent.com/793851/129330071-f79e384f-87c8-4fbe-a7b3-245e75f89920.png">

Please check [this sandbox](https://codesandbox.io/s/nervous-bardeen-x833d) for live example.

## Specifications

* Circuit version `3.0.1`

**Comment by connor-baer** [comment]
The Inputs use box-shadow for the border which extends beyond the element width and thus gets cut off by the `overflow: hidden` from the `useCollapsible` hook. Changing it to `overflow-y: hidden` should resolve it.

Fixed in 4b4776c.

**Comment by mykolaharmash** [comment]
Nice, thank you for a quick fix 🙌

**Comment by mykolaharmash** [comment]
Hm. Just tried to updated styles manually and at least in Chrome it does not work as expected and inputs are still cropped. If I set only `overflow-y: hidden;`, Chrome for some reason implicitly sets `overflow-x: auto;` and even setting `overflow-x: visible;` has no effect. At the same time `overflow-y: clip;` works as expected 🤷‍♂️

Could you please double-check? Thank you!

**Comment by connor-baer** [comment]
@mykolaharmash I must admit that I didn't test the fix and just assumed it would work 🙈 That's annoying. `overflow: clip` has very little [browser support](https://caniuse.com/css-overflow). 

I'm not sure there's anything else we can do in Circuit UI to fix this. I'd suggest adding a 2px padding to the collapsible content and a 2px negative margin on its container.

**Comment by mykolaharmash** [comment]
Right, that's exactly the workaround I use in my case, just 1px horizontal padding. We can close this then I guess.

**Comment by mykolaharmash** [comment]
Maybe one last thing. Would it be possible to set `overflow: hidden` only when the animation is in progress? Because right now focus rings are also cropped by the collapsible container.

**Comment by connor-baer** [comment]
I suggested 2px to account for the Input's focus state 🙂 Of course the Button's focus ring would still be cropped 😞

> Would it be possible to set overflow: hidden only when the animation is in progress?

Maybe. I'll look into this next week when I have more time. A PR would also be welcome 😉
