### ISSUE TITLE
Allows the `required` attribute in RadioButtonGroup component

### ISSUE THREAD

**Issue by long-lazuli** [sumup-oss/circuit-ui#1224]
## Component to amend

RadioButtonGroup

## Visual

<img width="227" alt="image" src="https://user-images.githubusercontent.com/1178625/137716995-a9b7ea24-e477-4907-a76d-2775e4045484.png">

## Context

This component's property `required` is not reflected in children (`input[radio]`).
I intend to make a PR resolving this.

I create this issue to discuss about it. Maybe there is some edge cases I don't see.

**Comment by robinmetral** [comment]
Fixed in #1225, released in `@sumup/circuit-ui@4.1.7`. Thanks @long-lazuli!
