### ISSUE TITLE
Col component controls crash Storybook

### ISSUE THREAD

**Issue by dmitri-suvorov-sumup** [sumup-oss/circuit-ui#1251]
## Describe the bug

An error appears in the dev console when clicking the "Controls (2)" button.
![Screenshot 2021-11-05 at 17 27 09](https://user-images.githubusercontent.com/53574544/140536132-a4e604f4-20db-4b78-98a2-c0d5d8b6f767.png)

## Steps to reproduce

1. Go to https://circuit.sumup.com/?path=/story/layout-grid-col--base
2. Click on "Controls (2)"
3. See error in the dev console

## Expected behavior

No error appears.

## Specifications

* Browser: Chrome 95.0.4638.69
* OS: macOS Big Sur 11.6.1

## Screenshot
![Screenshot 2021-11-05 at 17 26 36](https://user-images.githubusercontent.com/53574544/140536431-38117aa5-0eed-46ef-93bf-829a2e022c8e.png)

**Comment by robinmetral** [comment]
Thank you for reporting—fixed in 91e3b2a
