### ISSUE TITLE
unnecessary rerender of popover component on scroll event

### ISSUE THREAD

**Issue by AndreeWille** [sumup-oss/circuit-ui#1327]
## Describe the bug

When using the Popover Component it gets rerendered on scroll event which makes sense in order to position the popover. Unfortunately this not only happens when the popover is visible but also when the popover is hidden.

## Steps to reproduce

1. Go to [(https://circuit.sumup.com/?path=/story/components-popover--base)](https://circuit.sumup.com/?path=/story/components-popover--base)
2. resize the browser window so that the browser scoll bar appears next to the component
3. Scroll up and down and chrome dev tools shows that the popover gets repositioned on every scroll. Also when you active React Dev Tools -> Components -> General -> Highlight updates when components render you visually see that it gets rerendered on every scroll

## Expected behavior

Popover gets not rerendered when not visible.

## Specifications

* Version: 
* Browser: Chrome 96.0.4664.110
* OS: macOS 12.1

## Additional context

https://user-images.githubusercontent.com/588343/147077256-40d7ce28-ef97-4e13-a7d2-e57d44916e22.mov

**Comment by robinmetral** [comment]
Should be fixed by #1328, will be in 4.6.1.

@AndreeWille feel free to upgrade Circuit in the merchant dashboard (you can also apply the same fix to the local implementation of the Popover), and let me know if this fixes the performance issues!

**Comment by AndreeWille** [comment]
thats huge! thanks a lot for fixings this immediately!
