### ISSUE TITLE
Contributor License Agreement: Login with Github does not work for me

### ISSUE THREAD

**Issue by AndreeWille** [sumup-oss/circuit-ui#1378]
## Summarize the question

I can't accept Contributor License Agreement because the login with Github does not work for mes

## Context

https://user-images.githubusercontent.com/588343/150744238-600358cc-c73d-4c52-aa26-477c99f96a91.mov

![Screenshot 2022-01-24 at 09 06 12](https://user-images.githubusercontent.com/588343/150744584-c074b473-67c7-4ab5-b3ed-815a84ead795.png)
## Specifications

* Browser: Latest Firefox and latest Chrome
* OS: macOs 12.1

**Comment by robinmetral** [comment]
Thank @AndreeWille, yes we're aware of this. We'll look into the issue with our CLA bot—feel free to ignore it for now, since you're employed by SumUp you don't need to sign it 🙂
