### ISSUE TITLE
Center (layout)

### ISSUE THREAD

**Issue by sumius** [sumup-oss/circuit-ui#1452]
## Visual

<img width="1184" alt="Screenshot 2022-02-24 at 18 21 36" src="https://user-images.githubusercontent.com/98822962/155696676-1e621b00-5064-457a-8885-552bd920e1f5.png">

```jsx
const centerStyles = () => css`
  ${spacing({ top: 'zetta' })} // optional prop?
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
```

## Context

Centering content is a common task and I've seen a lot of duplicated code for solving this. My proposal is to create a layout component that can be used in these cases, similar to the code snippet above. It could include more optional props to cater for more use cases.

## State

No state.

## Progressive enhancement

This is just about centering a single item, so the behaviour on smaller screens would be the same. We could consider having an alignment component that excepts several items, but then the scope increases and is another discussion all together.

**Comment by robinmetral** [comment]
This makes sense I think! It seems similar to our style mixins to me, a small utility that avoids having to repeat common code.  I'd add it as a mixin rather than a component to avoid the extra DOM nesting. Other thoughts @sumup-oss/design-system-codeowners?

**Comment by sumius** [comment]
> 

Mixin is a good idea!

**Comment by connor-baer** [comment]
Yeah, adding this as a [style mixin](https://github.com/sumup-oss/circuit-ui/blob/main/packages/circuit-ui/styles/style-mixins.ts) sounds good. 

Sidenote: Is the screenshot above using the [NotificationFullscreen](https://circuit.sumup.com/?path=/docs/notification-notificationfullscreen--base) component?

**Comment by sumius** [comment]
> Sidenote: Is the screenshot above using the [NotificationFullscreen](https://circuit.sumup.com/?path=/docs/notification-notificationfullscreen--base) component?

Yes, it does @connor-baer

**Comment by robinmetral** [comment]
Do you want to submit a PR for it @sumius?
