### ISSUE TITLE
Tooltip is broken in Storybook docs

### ISSUE THREAD

**Issue by dmitri-suvorov-sumup** [sumup-oss/circuit-ui#1466]
## Describe the bug

The tooltip component is rendered with an offset in Storybook docs.

## Steps to reproduce

1. Go to [circuit.sumup.com](https://circuit.sumup.com/?path=/docs/components-tooltip--bottom-right)

## Expected behavior

The tooltip is rendered correctly.

## Specifications

* Browser: Google Chrome 98.0.4758.109
* OS: macOS Big Sur 11.6.4

# Screenshot
![Screenshot 2022-03-04 at 12 38 39](https://user-images.githubusercontent.com/53574544/156751549-96c91cba-434c-4af9-bdc9-2a15d37f2dbb.png)

**Comment by robinmetral** [comment]
Hey @dmitri-suvorov-sumup, thanks for reporting! This has low priority since the bug doesn't seem to affect the actual component, and the component is on the backlog to be rebuilt using Floating UI (ex-Popper.js). A contribution is always welcome though 🙂

**Comment by connor-baer** [comment]
Closing based on @robinmetral's [comment above](https://github.com/sumup-oss/circuit-ui/issues/1466#issuecomment-1062743862).
