### ISSUE TITLE
Do form components work with uncontrolled forms?

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1581]
## Summarize the question

We've had reports of the `SelectorGroup` not working with uncontrolled forms (it expects a mandatory `value`).

We should make sure that all our form components work with both controlled and uncontrolled form strategies.

## Context

☝️ 

## Specifications

n/a

**Comment by robinmetral** [comment]
@connor-baer has been looking into this and it should be solved in an upcoming release. Keeping open for now

**Comment by connor-baer** [comment]
Good news! Circuit UI [v6.9](https://github.com/sumup-oss/circuit-ui/releases/tag/%40sumup%2Fcircuit-ui%406.9.0) enables the SelectorGroup, RadioButtonGroup, and the new CheckboxGroup components to be used as uncontrolled components using the new `defaultValue` prop.
