### ISSUE TITLE
SelectorGroup options should all have the same height

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1582]
## Describe the bug

If an option in a `SelectorGroup` has a label that wraps on multiple lines, the options will have different heights.

<img width="1355" alt="Screenshot 2022-05-12 at 12 26 24" src="https://user-images.githubusercontent.com/35560568/168064890-7845626f-af86-47dd-baa3-c3738360398f.png">

## Steps to reproduce

1. Go to the Storybook
2. Make the label of one of the options longer

## Expected behavior

All options should have the same height.

## Specifications

n/a

## Additional context

Fixed locally in an app using:

```tsx
const StyledSelectorGroup = styled(SelectorGroup)`
  /* makes all option wrappers stretch */
  align-items: stretch;

  /* ...but the label div won't take up the entire height by default */
  label {
    height: 100%;
  }
`;
```

**Comment by jmoldyvan** [comment]
I might be able to help, which file is it in?

**Comment by robinmetral** [comment]
That's really cool @jmoldyvan! 🎉 We have a small glitch in our CLA bot at the moment, let us address it and I'll get back to you once we're ready to accept contributions again 🙂
