### ISSUE TITLE
[Input] Invalid message styling improvement

### ISSUE THREAD

**Issue by briannailiev** [sumup-oss/circuit-ui#1587]
## Component to amend

[Input (invalid)](https://circuit.sumup.com/?path=/docs/forms-input--invalid)

## Visual

Currently, when the page is smaller the invalid message for the input field breaks into two lines but doesn't seem aligned. The screenshot below offers a corrected appearance on the left and the current appearance on the right

![Screenshot 2022-06-01 at 10 47 09](https://user-images.githubusercontent.com/49642187/171443314-8f12e780-a58e-4026-8df6-0a56454534a1.png)

## Context

I think my suggestion makes the invalid message a bit more pleasing to the eye

**Comment by connor-baer** [comment]
Which version of Circuit UI are you using? 

I am unable to reproduce the exact styling from your screenshot in [Storybook](http://localhost:6006/iframe.html?id=forms-input--invalid&args=&viewMode=story). I suspect that something else is interfering with your styles or you're using an outdated version of Circuit UI. Here's what I'm seeing:

<img width="371" alt="Screenshot 2022-06-01 at 16 07 21" src="https://user-images.githubusercontent.com/11017722/171501951-1c486a1b-e696-4f57-b2ac-6409761307e5.png">

As you can see, the line height and horizontal alignment look much better. Granted, the text would look better if it didn't wrap around the icon and instead had a consistent alignment, as you suggested. We'd welcome a PR to improve this!

**Comment by briannailiev** [comment]
Thanks for checking! I'm not sure which version we replicated in our project (unfortunately, we're still not using Circuit UI directly), but I will compare the published version to what we've replicated to make sure we're reflecting the correct properties. 

I will do my best to contribute with a little PR :)
