### ISSUE TITLE
The NotificationModal should support async actions

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1628]
## Component to amend

`NotificationModal`

## Visual

No changes.

## Context

The component should support a use case where clicking an action button calls an API. Instead of closing the modal immediately, the button should receive a loading state and loading label and close when the promise resolves.

The modal closing behavior is defined here:

https://github.com/sumup-oss/circuit-ui/blob/b87093641121522c6d58e08cd85f84174c69c737/packages/circuit-ui/components/NotificationModal/NotificationModal.tsx#L180-L185

**Comment by connor-baer** [comment]
What should happen when the promise rejects? How would the error be communicated to the user?

**Comment by MarioSerano** [comment]
Hey, I'm interested in working on this if there's no one taking the tasks already.

> Excellent question—I'll check with the team that wanted to use this what their idea was here.

Also, in context of this, mentioned by @robinmetral, is there any followup from the team yet?

Thank you! ✌🏻

**Comment by robinmetral** [comment]
Hey @MarioSerano, thanks a lot for reaching out! A contribution would be awesome, unfortunately our CLA bot isn't working at the moment 🙈 I'm looking at fixing it, and I'll let you know when we're ready to accept external contributions again! (and when I have updates from the team)

Just curious: are you using Circuit UI in one of your projects? Or was there another reason you'd like this fixed?

**Comment by MarioSerano** [comment]
Hey, thanks for the reply @robinmetral!

Hopefully the CLA bot is fixed soon so I can possibly contribute soon!

I have not used Circuit UI in one of my projects, unfortunately. I want to try to contribute in an open source project, so I looked through explore over things I can actually do and I stumble upon Circuit UI and I've worked on my personal component library before, so I was hoping that I could lend a hand!

**Comment by a5e** [comment]
Hi there, we have a usecase where we would need Circuit to not close the `NotificationModal` by itself.

```
import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

import { useNotificationModal } from '@sumup/circuit-ui';

import { useAPICountryAppConnectRequest } from '@sonar/domains/AppMarket/hooks/useAPICountryAppConnectRequest';
import { useCatalogContext } from '@sonar/domains/AppMarket/pages/Catalog/Context';

import { useApplicationContext } from '../../Context';

const useConfirmCustomerModal = () => {
  const { t } = useTranslation();
  const { setModal, removeModal } = useNotificationModal();
  const { app } = useApplicationContext();
  const { selectedStore: store } = useCatalogContext();

  const { isLoading, mutateAsync: confirmCustomerMutate } = useAPICountryAppConnectRequest({
    appId: app?.id,
    countryCode: store?.country,
  });

  const saveHandler = useCallback(async () => {
    if (!store) return;

    await confirmCustomerMutate({
      storeId: store.id,
    });
    removeModal();
  }, [removeModal, confirmCustomerMutate, store]);

  const openModal = useCallback(() => {
    setModal({
      image: {
        src: '/customer.svg',
        alt: t`appMarket.customer`,
      },
      headline: t('appMarket.confirmCustomerModal.title'),
      body: t('appMarket.confirmCustomerModal.description', {
        name: app?.informations?.applicationName,
      }),
      actions: {
        primary: {
          children: t('appMarket.confirmCustomerModal.buttons.confirm'),
          onClick: saveHandler,
          'data-testid': 'confirmCustomerModalButton',
          isLoading,
          loadingLabel: t('appMarket.confirmCustomerModal.loadingLabel'),
        },
        secondary: {
          children: t('appMarket.confirmCustomerModal.buttons.cancel'),
          onClick: removeModal,
          'data-testid': 'closeCountryModalButton',
          disabled: isLoading,
        },
      },
      closeButtonLabel: 'close',
    });
  }, [setModal, app, removeModal, t, isLoading, saveHandler]);

  return { openModal, removeModal };
};

export { useConfirmCustomerModal };
```

We discussed with Robin, having a prop to disable the automatic closing action would be helpful in our case.

**Comment by MarioSerano** [comment]
I'll work on that! @a5e

**Comment by MarioSerano** [comment]
Do you then think if it's great to have something like a `disableAutomaticClosing` prop for every action in the `actions` prop (like `primary` and `secondary`) that exist in `NotificationModalProps` type? 

Also, does this result in the resolution of the issue, with it being having the user's control to call `removeModal` from the `useNotificationModal` API?
