### ISSUE TITLE
Reimplement the Tooltip component using Floating UI

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1676]
## Component to amend

`Tooltip`

## Visual

The component will look similar to the [current Tooltip component](https://circuit.sumup.com/?path=/docs/components-tooltip--base). Visuals should remain the same unless otherwise noted (including default placements, etc).

| Name | Screenshot | Details |
| --- | --- | --- |
| Overview | <img width="995" alt="" src="https://user-images.githubusercontent.com/35560568/180206913-d9a6916f-e752-4517-859a-2f35f1a618d7.png"> | n/a |
| Padding | <img width="829" alt="" src="https://user-images.githubusercontent.com/35560568/180207114-59432ecd-837f-4e8e-85bb-4a8258ecf59e.png"> | Horizontal padding of 12px, vertical padding of 8px |
| Arrow dimensions | <img width="710" alt="" src="https://user-images.githubusercontent.com/35560568/180207243-64beb532-5ff3-4060-8a35-422b043d03cf.png"> | 16px (main axis) by 8px (cross axis) arrow, 12px from the edge of the Tooltip |

## Context

There are two main objectives to this update:

- tweak the component visuals to match design specs (no shadow, rounded arrow tip)
- make the Tooltip accessible (🚧 more info)

## Release

The component should be released in a 5.x version of Circuit UI. The current Tooltip is used in a significant number of components, so having a way to use the new Tooltip as an "opt in" feature

The current version of the Tooltip should be deprecated.

In v6, the legacy Tooltip should be deleted and replaced by the new Tooltip (see #1677).

**Comment by connor-baer** [comment]
https://sarahmhigley.com/writing/tooltips-in-wcag-21/

**Comment by robinmetral** [comment]
@connor-baer you beat me to it 😉

**Comment by connor-baer** [comment]
The experimental Tooltip and Toggletip components are available in [@sumup/circuit-ui@8.6.0](https://github.com/sumup-oss/circuit-ui/releases/tag/%40sumup%2Fcircuit-ui%408.6.0).
