### ISSUE TITLE
Update browser support policy

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1680]
SumUp has changed its browser support policy ([internal link to repo](https://github.com/sumup/legacy-browsers)) and the [browser support docs in Circuit UI](https://circuit.sumup.com/?path=/docs/introduction-browser-support--page) should be adapted to reflect it.

## New browser support policy

| Supported | Unsupported |
| --- | --- |
| Chrome 63+ | Chrome <63 |
| Firefox 67+ | Firefox <67 |
| Edge 79+ | Edge <79 |
| Safari iOS 11.0+ | Safari iOS <11.0 |
| Safari macOS 11.1+ | Safari macOS <11.1 |
| Opera 50+ | Opera <50 |
| Samsung Internet 8.2+ | Samsung Internet <8.2 |
| | Internet Explorer |
| | Android Webview |

## Update code and configs

We need to identify which features are made available to use under the updated support policy, and can replace old workarounds we find in the Circuit UI codebase.

We should also look into whether we can update our tsconfigs to point to an ES version above the current `es2017`.

**Comment by connor-baer** [comment]
> We should also look into whether we can update our tsconfigs to point to an ES version above the current es2017.

I did consider this when choosing the new support policy. While a majority of features in `ES2018` are available in the supported browsers, I think it's safer to stick with `ES2017` for now.
