### ISSUE TITLE
Add optional trailing chevron icon to the Button component

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1681]
## Component to amend

`Button`

## Visual

<img width="793" alt="" src="https://user-images.githubusercontent.com/35560568/180421846-5908c2aa-119b-463d-a7c3-eff96ad24c46.png">

## Context

The `Button` component should optionally accept a chevron as a trailing element, when it is used as e.g. a `Popover` reference element. Currently, the component only accepts passing a leading `icon`.

The API for this new feature is still to be discussed.

**Comment by connor-baer** [comment]
The Button component added support for a trailing `navigationIcon` in [v7.5](https://github.com/sumup-oss/circuit-ui/releases/tag/%40sumup%2Fcircuit-ui%407.5.0).
