### ISSUE TITLE
Use progress element for ProgressBar component

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#1718]
## Component to amend

`ProgressBar`

## Purpose

The `ProgressBar` component [currently](https://github.com/sumup-oss/circuit-ui/blob/55438314d098bcd5885256e89f5d977d82b6b65e/packages/circuit-ui/components/ProgressBar/ProgressBar.tsx#L187) uses a `span` element under the hood. It also has the `max` and `min` attributes, which are not allowed for a span element.

The component should ideally be amended to use a native HTML [`progress`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) element under the hood.

(This will require more accessibility research on the progress indicator pattern)

**Comment by connor-baer** [comment]
Is the `role="progressbar"` attribute not sufficient? 

For reference: https://github.com/sumup-oss/circuit-ui/pull/1276/files#r751623708.

**Comment by robinmetral** [comment]
Not really:

1. using `role="progressbar` doesn't make it valid to use e.g. the `max` attribute on the `span` (there's a replacement [`aria-valuemax`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuemax) which we're using already, so we could basically remove `max` here)
2. ...which brings us to the question of why this isn't using native HTML semantics instead of ARIA—cf. [the first rule of ARIA](https://www.w3.org/TR/using-aria/#rule1) and yadda yadda 

So clarify: the current implementation works fine, so this isn't a very urgent fix. It's just that the implementation doesn't follow best practices and contains invalid HTML 🙂

**Comment by robinmetral** [comment]
This is still relevant and would be a nice fix! Could be a good first issue for someone wanting to contribute to Circuit UI.
