### ISSUE TITLE
ref is not forwarded to the DOM element in the `NotificationInline` component

### ISSUE THREAD

**Issue by tranhoangan22** [sumup-oss/circuit-ui#1828]
## Component to amend

The `NotificationInline` component.

## Visual

NA.

## Context

Currently we cannot pass a `ref` as `prop` in the `NotificationInline` component to be passed down to the respective DOM element. Being able to reference the component and its child element is helpful since we'd be able to use the DOM element's ref to do stuff like checking if the component is in the viewport.

Ref forwarding can be done with [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html).

**Comment by robinmetral** [comment]
Note that this probably is the same for other components—let's address it in a single PR at least for all 4 notification components.

As a rule all components should forward refs to either the wrapping element (for patterns like notifications) or to the core HTML element (such as the `input` for inputs)
