### ISSUE TITLE
Inconsistent Button size

### ISSUE THREAD

**Issue by herberthenrique** [sumup-oss/circuit-ui#277]
Hi everyone :)
I have one question, working in Partner Portal we found out the following issue:

`Button` on the size `KILO` has `font-size: 15px`
`PlainButton` on the size `KILO` has `font-size: 13px`

Is this difference something meant to be "By Design"?  
Or is this a bug in our Buttons sizes?  🤔 

IMHO: Size props should respect font-size according to the theme (which says that `text` should be `13px` on `kilo` size).
WDYT?

**Comment by larimaza** [comment]
Closing this issue because now both base and plain buttons have a font size of 16px.
