### ISSUE TITLE
Develop standard component API patterns

### ISSUE THREAD

**Issue by felixjung** [sumup-oss/circuit-ui#342]
Analyze existing component APIs and come up with some standard API patterns we want to use throughout the library.

**Comment by felixjung** [comment]
Move to non-boolean props. Boolean props are bad because they are non-explicit. Enums are better. For example, what should a Button with `primary` and `secondary` props render? Instead use `type="primary"`.

**Comment by felixjung** [comment]
Using references in React has changed over time and different libraries have used different approaches.

Ideally we can move on and use the native forwardRef everywhere.

**Comment by connor-baer** [comment]
**Use consistent prop names.** Some components use different prop names for similar use cases, e.g. `onToggle` vs `onChange`. We should agree on a consistent naming convention. 

Edit: I've decided on `onChange` and made the required deprecations in #470.

**Comment by connor-baer** [comment]
**Allow custom props on all components.** Functional and class components should forward any additional props to their outermost child component. This is important for `data-testids` and custom styles using Emotion's `styled` function.

**Comment by connor-baer** [comment]
Closing in favor of #525, #526, and #527.
