### ISSUE TITLE
Add typings for flow and Typescript

### ISSUE THREAD

**Issue by felixjung** [sumup-oss/circuit-ui#352]
Adding these would make adoption easier for consumers of the library.

**Comment by YannickFricke** [comment]
Any news on this? :)
Would love to have type definitions for it! :)

**Comment by fernandofleury** [comment]
Hey @YannickFricke it's part of our v2 milestone. We are actually working on it! 😄

**Comment by connor-baer** [comment]
Closing in favor of #516.
