### ISSUE TITLE
Migrate Circuit UI to Typescript or flow

### ISSUE THREAD

**Issue by felixjung** [sumup-oss/circuit-ui#353]
This should ideally be done incrementally.

**Comment by connor-baer** [comment]
In my opinion, this should be part of v2. Let's get out a stable (read bug-free) v1 quickly and then iterate.

**Comment by fernandofleury** [comment]
Well, @connor-baer has a point. specially considering that apart from @herberthenrique we are not using any typings at all.

**Comment by connor-baer** [comment]
Closing in favor of #516.
