### ISSUE TITLE
Extract Design Tokens into a separate package

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#511]
Currently, design variables are duplicated across our platforms. For example, our color palette lives [in JavaScript in Circuit UI](https://github.com/sumup-oss/circuit-ui/blob/canary/src/themes/circuit.js), and in XML in Android.

When a value changes, developers have to manually update it across our apps. This takes time and can also cause inconsistencies.

## A solution: design tokens

Design tokens are the most primitive design values in our design system. They include our color palette but also font sizes, font weights, spacings, etc.

A token consists of a name and a value, for example:

```
PrimaryColor: "#3388FF"
```

> Design tokens are a single source of truth for design variables that is updated by designers, and automatically transformed to be consumed by all platforms.

### 1. A single source of truth
Design tokens are typically in a platform-agnostic format such as JSON or YAML. They can therefore be the source of truth across platforms.

### 2. Updated by designers
Design tokens shouldn’t be updated by developers. These primitive values should be owned by designers. Ultimately, to make the process of updating design tokens easier, they could even be sourced from a design tool such as Figma.

### 3. Automatically transformed
Theming variables need to have a different format depending on the platform. For example, colors on the web could be RGB or HEX, but they need to be formatted as 6- or 8-digit HEX in Android.
Tools such as style-dictionary or theo can be used to automatically transform design tokens to be consumed by any platform, based on their requirements.

## Design tokens and Circuit UI

Design variables for the web currently live in Circuit UI’s [`circuit.js`](https://github.com/sumup-oss/circuit-ui/blob/canary/src/themes/circuit.js) file.

As a first step towards design tokens, we could extract these primitives into a separate package named `circuit-theme`.

This package will be available on NPM. The variables it generates for the web will be consumed by Circuit UI, and it will make other formats available to the native apps.

This has several advantages:

- Automatic transforms for different platform-specific formats
- Better versioning of theme values
- More accessible to designers (with automatic release from Figma in the future)
- Eventually, custom theming for Circuit UI

**Comment by danilovaz** [comment]
There are good libraries for this. I use Style Dictionary and it works very well.

https://github.com/salesforce-ux/theo

https://github.com/amzn/style-dictionary

https://diez.org/

**Comment by connor-baer** [comment]
Closed by #572.
