### ISSUE TITLE
Replace boolean props with enums

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#525]
## Motivation

As explained in [this article](https://spicefactory.co/blog/2019/03/26/how-to-avoid-the-boolean-trap-when-designing-react-components/) and many others, enum props are preferable to boolean flags as they're mutually exclusive and easier to type.

For example, what should a `<Button />` with `primary` and `secondary` props render? Instead, it's preferable to use `variant="primary"`. Circuit UI already does this e.g. for sizes: `size={Button.KILO)`.

## Components to amend

- Button (primary vs secondary vs flat)
- List (ordered vs unordered)

_Originally posted by @felixjung in https://github.com/sumup-oss/circuit-ui/issues/342#issuecomment-450895590_

**Comment by larimaza** [comment]
What @connor-baer and I have discussed so far:
- Primary and secondary buttons should be passed in the "variant" Button prop;
- Flat button should be "absorbed" into secondary button, and deprecated;
- Plain button should be decoupled from the Button, being an anchor tag by default, and be categorized accordingly (but still retain the logic that can turn it into a button when needed).

Pending analysis with design team.
