### ISSUE TITLE
Select field does not get the top margin 4 when a label is above

### ISSUE THREAD

**Issue by nicosommi** [sumup-oss/circuit-ui#530]
## Describe the bug

If you design a form that have a combination of Input and Select with labels, the Input get a top margin of 4px, but the Select don't, resulting in things like this:

![circuit-select-2](https://user-images.githubusercontent.com/1702755/72979811-6cc0e580-3dd9-11ea-882c-b5043b6d858f.png)

Or even like this

![circuit-select-1](https://user-images.githubusercontent.com/1702755/72979852-7f3b1f00-3dd9-11ea-898e-1f10e2c9612d.png)

## Steps to reproduce

1. Go to https://sumup.de/kontaktform/
2. Scroll down to Form
3. See the error

## Expected behavior

I expect the Select to have the same spacing applied.

## Specifications

* Version: canary
* Browser: Chrome
* OS: Macos

## Additional context

We have it solved locally applying a style from the Label. I can tackle this myself if preferred.
Introduced on https://github.com/sumup-oss/circuit-ui/pull/502/commits/99219b7a3c70d877de3882fbfd3be64ea85da685

**Comment by connor-baer** [comment]
@nicosommi Thanks for the detailed report! Would be great if you could open a PR to fix it.

**Comment by connor-baer** [comment]
Resolved by #532 and released in v1.6.2.
