### ISSUE TITLE
UI for SearchInput component is broken on Safari

### ISSUE THREAD

**Issue by nikilok** [sumup-oss/circuit-ui#545]
## Describe the bug

The SearchInput and AutoCompleteInput in question is this one: https://circuit.sumup.com/?path=/story/forms-input-autocompleteinput--base

It appears this component is broken on Safari.

## Steps to reproduce

1. Visit the URL provided above in any version of Safari.

## Expected behavior

It is supposed to look the same irrespective of the browser.
![image](https://user-images.githubusercontent.com/6220175/74348388-e6356d80-4db2-11ea-8cbd-4b2596e1c823.png)

But it ends up looking like this on Safari.
![image](https://user-images.githubusercontent.com/6220175/74348430-fbaa9780-4db2-11ea-9840-25dea5012b98.png)

## Specifications

* Version: 13.0.5 (15608.5.11)
* Browser: Safari
* OS: Mac OS Catalina (10.15.3)

**Comment by larimaza** [comment]
I was investigating this issue and it seems like Safari's User Agent Stylesheet is overwriting our custom styles and applying `padding: 1px;` for all sides.

The weird thing is, I couldn't make our styles take precedence even with `!important`. 🤔 

![Screen Shot 2020-03-10 at 17 01 52](https://user-images.githubusercontent.com/25252211/76354261-e6148900-62f0-11ea-87a1-f571d4efa62f.png)

**Comment by marielakas** [comment]
Hey! This is already fixed but now we have a small issue with the search icon:

![Screenshot 2020-04-01 at 10 57 39](https://user-images.githubusercontent.com/4214288/78112984-b0eaea80-7407-11ea-8d6d-29913bd95d9b.png)

We need to add `margin: 0` to the native input and it'll work like a charm. Will fix it asap ;)
