### ISSUE TITLE
Clarification : Is that possible to have a secondary font ?

### ISSUE THREAD

**Issue by cyrilchapon** [sumup-oss/circuit-ui#556]
## Summarize the question

Is that possible to have a secondary font ?

## Context

Hey, thanks for this quality library, and docs !
I love emotion.js and I'm trying to find a component library to have a base for a brand new website.

Comparing, and considering circuit-ui; I fell here https://circuit.sumup.com/?path=/docs/advanced-theme--page and here https://circuit.sumup.com/?path=/docs/advanced-fonts--page

Which emphasis well on the themable approach of emotion, and its implementation inside circuit-ui.

Though, it's not that clear about the usage of some additional fonts.

For example; I like to have a serif font-stack, a sans-serif one, and a mono one.
For completeness; I'd even like to have 2 serif and 2 sans-serif (for rare cases).

Is that something possible ? I can't find anything else than the `default` font, even digging into the source-code.

**Comment by cyrilchapon** [comment]
EDIT: And btw; I made [this font-stack helper](https://github.com/cyrilchapon/font-stack) a couple weeks ago; and I'd be glad to have a contribution there ❤️

**Comment by connor-baer** [comment]
Hey @cyrilchapon! Thanks for your question. 

Circuit UI's default theme includes a `default` and a `mono` font stack, [as you can see here](https://github.com/sumup-oss/circuit-ui/blob/canary/src/themes/circuit.js#L206-L211). You can override these values with a custom font stack. 

Circuit UI is tailored to the use cases we have at SumUp and we don't plan on adding a `serif` font stack to the standard theme and built-in components any time soon. You could, however, add a `serif` font stack to your custom theme and use it in your own components.
