### ISSUE TITLE
Combine label with form input components

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#569]
## Component to amend

- Input
- Textarea
- Select

## ~Visual~

_This would be an API-only change. No visual changes (yet)._

## Context

In what context does your amendment solve a problem?

Form inputs always require a label for usability and accessibility. That's why I suggest merging the Label component into the Select, TextArea, and Select components. This has the following benefits:

- reduces the boilerplate for developers
- linking the input and label elements can be implemented internally to ensure that it's done properly
- the same approach is already used for Checkbox and RadioButton components

In the rare case that there shouldn't be a visible label, the label text can be hidden with a prop (e.g. `visuallyHideLabel`) while it remains accessible for screen reader users.

Furthermore, the design team is exploring [a new design for the inputs](https://www.figma.com/file/rXXmCtOOVZo6qyemUANZvb/WIP-Circuit-UI-Components?node-id=6015%3A8760) that visually integrates the label with the input. Merging the label into the input components paves the way for this design update.

![Design proposal where the label overlaps the outline of the input](https://user-images.githubusercontent.com/11017722/79452407-68772380-7fe8-11ea-9abb-262e6389f6a5.png)

## Implementation

Here's a code sample of the proposed changes:

```js
import { Label, Input } from "@sumup/circuit-ui";

const EmailInput = () => {
  const id = "email-input";
  return (
    <Label htmlFor={id}>
      Email
      <Input type="email" id="email" />
    </Label>
  );
};

// ...becomes...

import { Input } from "@sumup/circuit-ui";

const EmailInput = () => {
  return <Input type="email" label="Email" />;
};
```

We can introduce this as a non-breaking change in v2.x. If the `label` is provided, the input is wrapped in the label. If not, the input works as before and a warning is logged to the console.

**Comment by fernandofleury** [comment]
From a technical standpoint I have nothing to say honestly. The sample looks very refreshing compared to our current inputs. I do remember this way mostly due a design decision and not technical one. Are we past that then?

**Comment by connor-baer** [comment]
As far as I remember, the idea to separate the label from the input was to allow for different label styles and positioning. I haven't seen this in any of our applications and the proposal from the design team strives for consistency, so yeah, I think we're past that.
