### ISSUE TITLE
Upgrade to Storybook 6

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#578]
## Suggested technology

The [next major version of Storybook](https://github.com/storybookjs/storybook/issues/9311), our development environment & documentation tool, was released this week. Most notably, it greatly improves support for TypeScript and adds [Storybook Args](https://docs.google.com/document/d/1Mhp1UFRCKCsN8pjlfPdz8ZdisgjNXeMXpXvGoALjxYM/edit#heading=h.6mdg0tp8crgj), a new API for interactive component examples.

We've started to gradually migrate Circuit UI to TypeScript (#516). All changes and new components should be done in TypeScript. Upgrading Storybook now would make our lives a lot easier while enabling powerful new features.

**Comment by robinmetral** [comment]
Will this also solve the problem of the [Storybook Info Addon](https://github.com/storybookjs/storybook/tree/master/addons/info) not being compatible with TypeScript at the moment? Or should we handle it separately [as recommended by Storybook](https://storybook.js.org/docs/configurations/typescript-config/#using-typescript-with-the-tsdocgen-addon)?

**Comment by connor-baer** [comment]
Yes, that's the main reason I want to update asap. Storybook 6 will have no-config TypeScript support, so I prefer to upgrade rather than fight with the configuration myself.

(FYI, the Info addon has been replaced by the Docs addon, which has the same issue)

**Comment by robinmetral** [comment]
Perfect! I was going to start fixing the addon, but good to know that this will solve the issue. Are we waiting for the stable version to upgrade?

**Comment by connor-baer** [comment]
I started the upgrade in [`tech/storybook`](https://github.com/sumup-oss/circuit-ui/tree/tech/storybook-6) but ran into some issues that might have been fixed by now. If you wanna work on this, you could continue from there.
