### ISSUE TITLE
Remove AutoCompleteInput and AutoCompleteTags components

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#589]
## Component to amend

AutoCompleteInput
AutoCompleteTags

## Context

The components mentioned above provide an interface for users to pick from a list of provided options. I'd like to remove them from Circuit UI, for the following reasons:

1. The components' API does not cover all use cases (https://github.com/sumup-oss/circuit-ui/issues/568) and thus does not meet the standards that Circuit UI aspires to
2. The components are composed of other, low-level Circuit UI components and the third-party [Downshift](https://github.com/downshift-js/downshift) library. In [Atomic design](https://bradfrost.com/blog/post/atomic-web-design/) terms, this makes them _molecules_ while Circuit UI is meant to provide on _atoms_. 
3. Related, the use of the [Downshift](https://github.com/downshift-js/downshift) library means that the state logic is internal to the components where it is difficult to customize. This is what makes it difficult to address point 1. Circuit UI is meant to provide visual primitives and leave the (state) logic to the users.
4. The use of a third-party library increases maintenance work since we need to keep up with bug fixes and security issues. 
5. The components are each used only once across all SumUp apps ([ze-dashboard](https://github.com/sumup/ze-dashboard/search?q=AutoCompleteTags&unscoped_q=AutoCompleteTags) and [partner portal](https://github.com/sumup/partner-portal/search?q=AutocompleteInput&unscoped_q=AutocompleteInput).

## Migration

The components can be copied to the projects that currently use them before being removed from Circuit UI.

**Comment by cecisousa** [comment]
Hey, Connor!
Great points that you listed as reasons for deleting these two components, I totally agree with them.

Regarding the migration process, what could be the best approach for partner portal? For example: (1) open a ticket in our board, (2) prioritize it before Circuit UI v2 release, (3) "kind of" copy&paste the component file to our project and (4) migrate it to TypeScript? 🤔

**Comment by connor-baer** [comment]
@cecisousa Exactly, that's what I had in mind, too. You'll be able to simplify the component once it's integrated on the partner portal, and it should improve performance as well.
