### ISSUE TITLE
[RFC] Integrating Collector to Circuit UI

### ISSUE THREAD

**Issue by lucent1090** [sumup-oss/circuit-ui#614]
## Suggested technology

- What technology do you suggest we start using?
https://github.com/sumup/collector (will be open source soon)

- What problem does it solve?
Introduce standard tracking event interface to our component library.

## Components to be migrated (WIP) :

- [x] Button Click
- [x] Hamburger
- [x] Card with Header, close button
- [x] Clickable tag
- [x] Removable tag
- [x] Form, checkbox
- [x] Form, radioButton
- [x] Form, selector
- [x] Form, select
- [x] Form, toggle
- [x] CalendarTag
- [x] CalendarTagTwoStep
- [ ] Message (Do we have this in V2?)
- [x] Modal, onClose
- [x] Pagination
- [ ] Popover (Wait for migrating to function component)
- [x] Sidebar, onClose
- [x] Sidebar, NavItem
- [ ] Sidebar, Nav aggregator (Wait for migrating to function component)
- [ ] Table, sorting click (Wait for migrating to function component)
- [ ] Tabs (Wait for migrating to function component)
- [ ] Carousel 

## Up for discussion components: 
All typography
All layout
All icons
Badge
Blockquote
Card
Header
Hr
Image
List
Picture
Progress Bar
Spinner
Table
Tooltip

**Comment by connor-baer** [comment]
:tada: This issues has been resolved in version 2.0.0-beta.13 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@sumup/circuit-ui/v/2.0.0-beta.13)
- [GitHub release](https://github.com/sumup-oss/circuit-ui/releases/tag/v2.0.0-beta.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
