### ISSUE TITLE
[v2] Input with Icon is misaligned

### ISSUE THREAD

**Issue by fernandofleury** [sumup-oss/circuit-ui#645]
## Describe the bug

![image](https://user-images.githubusercontent.com/2780941/87950665-e5aeaa80-caa7-11ea-8d4d-3f7c914ac4ac.png)

You can see both icons & close button misaligneds.

## Expected behavior

Elements should be properly aligned inside the input.

## Specifications

* Version: 2.0.0-beta22
* Browser: Chrome
* OS: macOS Big Sur

**Comment by connor-baer** [comment]
Fixed by #647.
