### ISSUE TITLE
Integrate React Aria

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#657]
## Suggested technology

> [**React Aria**](https://react-spectrum.adobe.com/react-aria/getting-started.html) is a library of React Hooks that provides accessible UI primitives for your design system. It provides accessibility and behavior for many common UI components so you can focus on your unique design and styling. It implements adaptive interactions to ensure the best experience possible for all users, including support for mouse, touch, keyboard, and screen readers.

[React Aria](https://react-spectrum.adobe.com/react-aria/index.html) would replace some of our own custom code to ensure accessibility. This would drastically improve Circuit UI's accessibility since React Aria is well tested using different input devices and assistive technologies.

## Alternatives

The concept of splitting a component library into a state, accessibility, and UI layer is rather new. I'm not aware of any other projects that do something similar.

## Potential downsides

React Aria seems to rely heavily on JavaScript, e.g. to normalize focus states across browsers. However, it's impossible to create accessible, rich, interactive applications without JavaScript. The library size is small enough for the benefit it provides.

**Comment by oliviertassinari** [comment]
> Considering that we're planning to remove React as a dependency,

I'm curious what's the rationale for it?

**Comment by oliviertassinari** [comment]
Thanks for the context, I was considering using Preact as a light wrapper to expose web components.
