### ISSUE TITLE
CurrencyInput doesn't format controlled values correctly

### ISSUE THREAD

**Issue by robinmetral** [sumup-oss/circuit-ui#659]
## Describe the bug

The `CurrencyInput` doesn't format controlled values correctly.

<img width="800" alt="Screenshot showing the bug reproduced in Storybook" src="https://user-images.githubusercontent.com/35560568/89919738-f3190980-dbfb-11ea-89ad-73b5d21be3da.png">

## Steps to reproduce

1. Start Storybook
2. Add this story to `CurrencyInput.story.tsx`:

    ```typescript
    export const bug = () => (
      <BaseCurrencyInput
        label="Controlled values are wrongly formatted"
        locale="de-DE"
        currency="EUR"
        value={12.26}
      />
    );
    ```
3. See that the rendered value on mount is wrongly formatted as `1.226` (the decimal is ignored).

ℹ️ Note that the _actual_ value is still correct, so there are no amount issues. When touching the input, it will rerender and the value will be properly formatted.

## Expected behavior

Controlled values should be formatted properly.

## Specifications

* Version: 2.0.0
* Browser: reproduced on Chrome, also reported on Safari
* OS: MacOS

## Additional context

This is causing render issues in the merchant dashboard in production, when using a Circuit `CurrencyInput` with our controlled form library.

**Comment by connor-baer** [comment]
The values appear to be correct in Circuit UI, so this points into the direction of a bug in [`react-text-mask`](https://github.com/text-mask/text-mask). Indeed I've found [a report of another user](https://github.com/text-mask/text-mask/issues/806#issuecomment-483299109) that appears to describe this issue. There doesn't seem to be a fix or workaround for it yet.

**Comment by robinmetral** [comment]
@connor-baer seems like it - it might be time to move away from `react-text-mask`, since it's deprecated?

**Comment by connor-baer** [comment]
@robinmetral Yeah, that's a good idea. Is this something you're interested in working on? (`react-text-mask` suggests [`react-imask`](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask) as an alternative)

**Comment by robinmetral** [comment]
Happy to tackle it, but maybe we can put it up for grabs for people who want to do their first contribution 🙂 What do you think?

**Comment by robinmetral** [comment]
For the record, this looks good too: https://github.com/Gusto/react-masked-field

**Comment by fernandofleury** [comment]
@connor-baer could we prioritize this one and fix it? This looks quite confusing for the final user
