### ISSUE TITLE
ButtonGroup doesn't apply margin when children are different HTML elements

### ISSUE THREAD

**Issue by larimaza** [sumup-oss/circuit-ui#688]
## Component to amend

ButtonGroup

## Visual

First button is an `a` | Both buttons are `button`
-|-
<img width="431" alt="Screen Shot 2020-10-22 at 10 45 31" src="https://user-images.githubusercontent.com/25252211/96881473-aef48180-1454-11eb-90c0-4a2b2b0c0d87.png">|<img width="434" alt="Screen Shot 2020-10-22 at 10 45 45" src="https://user-images.githubusercontent.com/25252211/96881532-c03d8e00-1454-11eb-83fc-a02739cbc757.png">

## Context

The ButtonGroup should apply margins between the buttons inside it for all cases.
However, because of selectors like this:
```
.css-185ogu-button-group-button-group--right > button:not(:last-of-type), .css-185ogu-button-group-button-group--right > a:not(:last-of-type) {
    margin-bottom: 16px;
```
...when the first button is an anchor and the other is a button, the margin is not applied, since the `a` is the last of its type.

The proposal would be to use the broader selector `:last-child`, since it's unlikely that the ButtonGroup will have another child that isn't an `a` or a `button` (and if it has, it's a wrong use of the component).

**Comment by connor-baer** [comment]
Thanks for the report @larimaza! This is a tricky one: Emotion puts constraints on the use of `:first-child` and other CSS child selectors (https://github.com/emotion-js/emotion/issues/1178). Circuit UI needs to support SSR, so that's not an option.

The alternative is to iterate over the child elements with React's `Children.map`, clone each child, and add the styles to them explicitely. The problem here is that Emotion's `css` prop doesn't work with React's `cloneElement` function.

**Comment by larimaza** [comment]
Tricky indeed 😬 TBH, I don't love the idea of adding a spacer `div` any more than I love the idea of customizing margins in usage 🙈 

The other solution is also not very nice, but... We could add a margin to **every** child and then counter the last one's margin in the button group itself.

**Comment by connor-baer** [comment]
That's better indeed. Emotion doesn't restrict the `:last-child` selector. Very clever! 🧠

**Comment by robinjimenez** [comment]
@connor-baer I can work on work on this!
I've been checking the code and doing some tests, replacing `:last-of-type` with `:last-child` seems to do the trick for both bottom and right margins

**Comment by connor-baer** [comment]
@robinjimenez Awesome! 🙌 Could you open a PR with the changes, please?
