### ISSUE TITLE
Anchor tag inside Notification looks different than docs

### ISSUE THREAD

**Issue by larimaza** [sumup-oss/circuit-ui#689]
## Component to amend

Button (or Notification?)

## Visual

As `button` tag | As `a` tag
-|-
<img width="1440" alt="Screen Shot 2020-10-19 at 16 51 58" src="https://user-images.githubusercontent.com/25252211/96882528-c7b16700-1455-11eb-8d4e-8ce8c578bd8c.png">|<img width="1439" alt="Screen Shot 2020-10-19 at 16 51 50" src="https://user-images.githubusercontent.com/25252211/96882512-c3854980-1455-11eb-92c8-4eb543054f85.png">

## Context

The look on the left, which is the Notification component with a Button inside it, is the look previewed in the Circuit docs.
However, when the button is an `a` tag, it gets different styles, and I believe it should look the same as the `button` case.

I fixed this locally by adding `display: inline-flex` to the anchor button. I'm not sure if this style should be added to the button itself (and therefore affect all instances of buttons as anchor tags), or only to the Notification component as a parent.

**Comment by connor-baer** [comment]
Nice catch @larimaza. Curiously, the `button` Button seems to work as `inline-flex` even when using `flex`. Weird. You're right, the solution here is to change the Button to `display: inline-flex;` in Circuit UI. I'll open a PR in a few minutes.
