### ISSUE TITLE
Add popover menu component

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#723]
### Implementations in the wild

<img width="282" alt="Popover menu in product catalog" src="https://user-images.githubusercontent.com/11017722/100242327-f62ed000-2f34-11eb-8d0b-815862c4be5e.png">

<img width="247" alt="Popover menu on transaction history" src="https://user-images.githubusercontent.com/11017722/100242348-faf38400-2f34-11eb-8357-29fe18d02f02.png">

<img width="227" alt="Popover menu on sales page" src="https://user-images.githubusercontent.com/11017722/100242372-0050ce80-2f35-11eb-8c41-2b66bd431991.png">

### New design

[![New mobile and desktop designs](https://user-images.githubusercontent.com/11017722/113886672-29c21680-97c1-11eb-94ce-23adae91c18b.png)](https://www.figma.com/file/2yHC0dK9pFEhLsMxk62XZY/Circuit-UI-Web?node-id=5260%3A1973)

## Context

Popover menus are a common pattern to display additional actions commonly after clicking a button. The screenshots above are taking from SumUp's dashboard: each example is a different implementation, each with different problems. 

Popover menus are not as straightforward to implement as it might seem. 

- Focus needs to be moved to the menu once it has been opened.
- The popover should close when the user clicks outside of it or presses the `ESC` key.
- Each action item should use an appropriate HTML element (`button` or `a`).
- The (optional) icon should be hidden from or be accessible to screen readers.
- If the menu would overflow the viewport, it should move above the button used to open it.

The [Inclusive Components](https://inclusive-components.design/menus-menu-buttons/) website has a good tutorial for creating [accessible menus](https://inclusive-components.design/menus-menu-buttons/).

## State

The popover menu can be _hidden_ or _visible_.
The menu items can be _default_, _hovered_, or _pressed_.

<img width="293" alt="Menu item states" src="https://user-images.githubusercontent.com/11017722/113887080-7a397400-97c1-11eb-9ae1-bf59d4dd76c7.png">
 
## Progressive enhancement

On large viewports, the popover should be absolutely positioned, relative to its trigger button.
On small viewports, there might not be enough space to display the popover next to the button. Instead, the menu should be displayed as a bottom sheet, similar to the Modal component.

**Comment by robinmetral** [comment]
Thanks for the proposal and summing up some things to keep in mind when implementing this! Do you think we can extend the Popover component or do we need something new?

On your points, I generally agree, just have a couple of extra comments:

> The popover should close when the user clicks outside of it.

...and also on keypresses like `ESC`?

Also, is it the Popover menu's concern to close when an action in the menu is selected? (ex: button clicked)

> On small viewports [...] I suggest displaying the menu as a bottom sheet, similar to the Modal component.

I would agree with this, but what about the potential popover menu on a modal? Should we also handle this case or just prevent it?

**Comment by connor-baer** [comment]
Thank you for your thoughtful feedback, @robinmetral 🤗 

> Do you think we can extend the Popover component or do we need something new?

Good question! I intend to review the [Tooltip](https://circuit.sumup.com/?path=/story/components-popover--base) and [Popover](https://circuit.sumup.com/?path=/story/components-tooltip--base) components. If they live up to our quality standards we can build on top of them (I have my doubts about their accessibility though). I'd also like to do some research on how (much) these components are used. I suspect we can improve their API a bit. 

> ...and also on key presses like ESC?

Yes, good catch! I've added it to the proposal. 

> Also, is it the Popover menu's concern to close when an action in the menu is selected? (ex: button clicked)

This seems to be the most common behavior, so I would make it the default. Ideally, we provide an escape hatch to modify this behavior when necessary. Can you think of a use case when it shouldn't close automatically? 

> I would agree with this, but what about the potential popover menu on a modal? Should we also handle this case or just prevent it?

Another good point that I hadn't considered. I think this is a valid use case that we should support. I imagine it would layer on top of the modal. This is something we definitely should discuss with the design team. They need to create a polished design for this component anyway before we can start working on it.
