### ISSUE TITLE
Refresh Header component

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#793]
## Component to amend

👀 [View Header in Storybook](https://circuit.sumup.com/?path=/story/components-header--base)

Currently only used in SumUp's Partner Portal app. SumUp's Dashboard app uses a custom page header component which should be replaced with this one going forward.

### Design

The [header bar for Circuit UI Mobile](https://www.figma.com/file/lgvQDus1CRKC7heaA1EzkR/Circuit-UI-Mobile?node-id=488%3A4) is clearly defined with a beautiful design:

<img width="933" alt="Screen Shot 2021-01-29 at 09 29 47" src="https://user-images.githubusercontent.com/11017722/106250894-8a0e6800-6214-11eb-8d26-cda618bbacfa.png">

I propose to adopt a similar design for web on mobile and adapt it for desktop screens. The component should support the following elements:

- Hamburger button to access the side navigation
- Page title, small or large
- **New**: One or two global action buttons, "global" meaning they apply to the whole page (the Dashboard places some actions in the header that only apply to the first page element, these need to be (re)moved).
- **New**: A back button to navigate to the previous page. As our product offering grows and with it the complexity of our applications, we need a deeper navigation structure. The back button would potentially conflict with the hamburger button. Alternatively, we could rely on the browser's back button.

On the Dashboard, the page header is currently sticky when scrolling on mobile. Do we want to keep this behaviour? Make it optional? Re-appear when scrolling up? There's limited screen estate on mobile viewports, but the title provides useful context.

### API

- The component should be renamed to be more specific, e.g. HeaderBar, AppHeader, PageHeader. 
- The `mobileOnly` prop should be deprecated.

**Comment by mykolaharmash** [comment]
Agree, would be really nice to have something similar on the web. A couple of points on the back button functionality, from my experience implementing [back button for product editor](https://github.com/sumup/ze-dashboard/pull/3842).

* We cannot rely on browser's `window.history.back()` as the user might open the page directly and there will be no previous history.
* Right now we do not have a global routes hierarchy in the dashboard, meaning the back button by default does not know where to navigate to when clicked, every page needs to provide a custom handler, this makes API of the page header a bit less elegant. We might want to research global routing solutions or some conventions to follow for internal routes.
* We also need to think if it's ok for the back button to just replace the sidebar toggle on mobile, do we need some other way to pull the sidebar in this case?

**Comment by connor-baer** [comment]
The existing Header component will be marked as "legacy" in Circuit UI v7.
