### ISSUE TITLE
Upgrade to Emotion 11

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#795]
## Context

Emotion 11 was released some time ago:

> Emotion 11 is a slight evolution over Emotion 10. It focuses mainly on the developer experience, TS types improvements, switches internals to hooks, and to the new version of the parser that we use: Stylis.

[Read the full release post](https://emotion.sh/docs/emotion-11)

## Required work

This is a breaking change that needs to be done in a major release (probably v3). The migration itself should be pretty painless for Circuit UI Web and its users.

## Potential blockers

https://github.com/storybookjs/storybook/pull/13300

**Comment by itsezc** [comment]
Hey @connor-baer, is there any ETA on when we can expect this for canary?

**Comment by connor-baer** [comment]
Hey @itsezc! We're tentatively planning for a first prerelease of v3 in April/May which will include Emotion 11. Be aware that this is a **rough** estimate.

**Comment by connor-baer** [comment]
Closed by #1176.
