### ISSUE TITLE
Update Button shape

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#820]
## Component to amend

👀 [View Button component in Storybook](https://circuit.sumup.com/?path=/story/components-button--variants)

## Context

The brand team would like to adjust the rounded corners of buttons (turn it into a "pill") that would reflect the general brand shapes.

## Visual

[![Button](https://user-images.githubusercontent.com/11017722/108975934-4da12100-7687-11eb-8d61-e4c644537199.png)](https://www.figma.com/file/wZiA56Ab9kSi7dt2O7ID8k/Implementation-package-Button?node-id=42%3A523)

## Tasks

- Update the button border-radius
- Override the border-radius for buttons inside inputs and tags to keep their current shape (?)

**Comment by robinjimenez** [comment]
Hi! I can take a look at this! I'm a first-time contributor looking but I'm happy to help if nobody's working on it yet!

**Comment by connor-baer** [comment]
Hey @robinjimenez! Thanks for the offer! However, I've almost completed the task already. 

Would you be interested in working on another issue, such as https://github.com/sumup-oss/circuit-ui/issues/688?

**Comment by robinjimenez** [comment]
No problem @connor-baer! I'll have a look at that one, thanks! 👍
