### ISSUE TITLE
Incorrect navigation item expansion behaviour

### ISSUE THREAD

**Issue by hrstngrnvsmp** [sumup-oss/circuit-ui#907]
## Describe the bug

Incorrect navigation item expansion behaviour

## Steps to reproduce

1. Go to Dashboard with a merchant that has `sumup_card` feature toggle but doesn't have any active cards yet.
2. Click on SumUp Card or Business Account from the main navigation.
3. The SumUp Card or Business Account tab is getting a bit taller.

![image](https://user-images.githubusercontent.com/62241171/115509171-cd61fb00-a286-11eb-8406-64c28fa75dfc.png)

https://user-images.githubusercontent.com/62241171/115509222-dbb01700-a286-11eb-9c42-805a62b99044.mov

## Expected behavior

If the merchant doesn't have any active cards, the tab behaviour should remain in the same state as when it was inactive.

## Specifications

* Version:
* Browser: all
* OS: all

**Comment by letanure** [comment]
@hrstngrnvsmp I have a issue about that, looking at that now
