### ISSUE TITLE
RadioButton with long label not displayed properly

### ISSUE THREAD

**Issue by hris27** [sumup-oss/circuit-ui#934]
## Describe the bug

If a `RadioButton` has a long label and is viewed at a mobile resolution, the label gets wrapped but is not displayed properly.

<img width="298" alt="Screen Shot 2021-05-14 at 16 12 27" src="https://user-images.githubusercontent.com/9676303/118278324-8f957280-b4d2-11eb-8e13-80edfae096be.png">

## Steps to reproduce

1. Create a `RadioButton` (or `RadioButtonGroup`) with a long label
2. View it at 320px width mobile resolution

## Expected behavior

The label is wrapped properly and possibly the radio button is top aligned instead of center. Also maybe some padding can be introduced between items of a `RadioButtonGroup`.

<img width="298" alt="Screen Shot 2021-05-14 at 16 55 52" src="https://user-images.githubusercontent.com/9676303/118280881-48f54780-b4d5-11eb-8c66-2158daa23dc3.png">

## Specifications

* Version: 2.4.0
* Browser: all (looks somewhat better in Firefox)
* OS: all

**Comment by connor-baer** [comment]
I've addressed the alignment issue of the wrapped text in https://github.com/sumup-oss/circuit-ui/pull/936. 

The radio button element is meant to be center-aligned. 

If you'd like to add spacing between radio buttons when using the RadioButtonGroup component, you can add it using the `css` prop: 

```tsx

import { RadioButtonGroup, spacing } from '@sumup/circuit-ui';

const options = [
    { children: 'Apple', value: 'apple', css: spacing('bit') },
    { children: 'Banana', value: 'banana', css: spacing('bit') },
    { children: 'Mango', value: 'mango', css: spacing('bit') },
]

const Example = () => (
	<RadioButtonGroup 
		label="Choose your favourite fruit"
		options={options}
	/>
);
```

We'll look into adding some default spacing in Circuit UI v3.

**Comment by hris27** [comment]
Awesome 👏 Thanks, @connor-baer
